### PR TITLE
Add preprocess pipelines

### PR DESCRIPTION
**Pull request by dorukozturk**
gdal_merge.py script can be ignored. It is a gdal utility function that I downloaded from gdal's source. 
@mattphillipskitware It would be great if you could try to do an ingest. You can create an input directory with small number of files to test if it is working for you.

### CODE REVIEW

**Comment by mattphillipskitware** [comment]
@dorukozturk Hey so where did you get the 2017_30m_cdls.img file?  Is that on data.kitware.com?

Also on both Ubuntu 16.04 and 18.04, requirements.txt installation fails with:

Command "/home/matt.phillips/virtualenv/luigi/bin/python3 -u -c "import setuptool
s, tokenize;__file__='/tmp/pip-install-ykl8vjp4/GDAL/setup.py';f=getattr(tokenize
, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(comp
ile(code, __file__, 'exec'))" install --record /tmp/pip-record-38h0rgbg/install-r
ecord.txt --single-version-externally-managed --compile --install-headers /home/m
att.phillips/virtualenv/luigi/include/site/python3.5/GDAL" failed with error code
 1 in /tmp/pip-install-ykl8vjp4/GDAL/

**Comment by dorukozturk** [comment]
@mattphillipskitware I think it was part of the bundle that we got from Sergii. I can share it with you tomorrow. 

For the gdal issue I think you have to install the system gdal by:
```
sudo apt-get install gdal
```
before you install the python bindings.

**Comment by mattphillipskitware** [comment]
Well, there's no 'gdal' package per se, and I've already installed gdal-bin and libgdal-dev. :/

**Comment by dorukozturk** [comment]
Oh ok it is python-gdal or python3-gdal if you are on python3.

**Comment by mattphillipskitware** [comment]
:(

  Can't roll back GDAL; was not uninstalled
Command "/home/matt/.virtualenvs/luigi/bin/python3 -u -c "import setuptools, tokenize;__
file__='/tmp/pip-install-5t3xulu3/GDAL/setup.py';f=getattr(tokenize, 'open', open)(__fil
e__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))
" install --record /tmp/pip-record-h_c1azk7/install-record.txt --single-version-external
ly-managed --compile --install-headers /home/matt/.virtualenvs/luigi/include/site/python
3.6/GDAL" failed with error code 1 in /tmp/pip-install-5t3xulu3/GDAL/


I think there is no more annoying/difficult install than gdal...

**Pull request merged**
